export const ADD_TRIANGLE = "ADD_TRIANGLE";
export const REMOVE_TRIANGLE = "REMOVE_TRIANGLE";
export const CLEAR_TRIANGLES = "CLEAR_TRIANGLES";
export const ADD_RANDOM_TRIANGLE = "ADD_RANDOM_TRIANGLE";
